### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by darshpatel27** [mrodalgaard/atom-todo-show#106]
TypeError: undefined is not a function
  at Function.module.exports.ShowTodoView.content (/home/darshan/.atom/packages/todo-show/lib/todo-view.coffee:12:35)
  at Function.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
  at Function.View.buildHtml (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at ShowTodoView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
  at ShowTodoView.ScrollView (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
  at new ShowTodoView (/home/darshan/.atom/packages/todo-show/lib/todo-view.coffee:42:5)
  at /home/darshan/.atom/packages/todo-show/lib/show-todo.coffee:83:13
  at wrappedOpener (/usr/share/atom/resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:366:19)
  at Object.module.exports.show (/home/darshan/.atom/packages/todo-show/lib/show-todo.coffee:108:20)
  at atom-workspace.disposables.add.atom.commands.add.todo-show:find-in-project (/home/darshan/.atom/packages/todo-show/lib/show-todo.coffee:72:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

**Comment by mrodalgaard** [comment]
When does this occur? What version of Atom are you using? Was you not prompted with an error report notification (when you click this it'll create a full error report with stack trace, packages installed and atom versions)?

**Comment by pwollstadt** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.3
**Thrown From**: [todo-show](https://github.com/mrodalgaard/atom-todo-show) package, v1.4.0


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/patriciaw/.atom/packages/todo-show/lib/todo-view.coffee:12

TypeError: undefined is not a function
  at Function.module.exports.ShowTodoView.content (/home/patriciaw/.atom/packages/todo-show/lib/todo-view.coffee:12:35)
  at Function.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
  at Function.View.buildHtml (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at ShowTodoView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
  at ShowTodoView.ScrollView (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
  at new ShowTodoView (/home/patriciaw/.atom/packages/todo-show/lib/todo-view.coffee:42:5)
  at /home/patriciaw/.atom/packages/todo-show/lib/show-todo.coffee:83:13
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:442:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:375:19)
  at Object.module.exports.show (/home/patriciaw/.atom/packages/todo-show/lib/show-todo.coffee:108:20)

```

### Commands

```
     -0:23.5.0 application:open-file (atom-pane.pane.active)
     -0:01.7.0 todo-show:find-in-open-files (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-python-test, v0.1.5
autocomplete-python, v0.5.3
git-diff-details, v0.18.0
language-matlab, v0.1.1
linter, v1.11.4
linter-flake8, v1.13.0
markdown-scroll-sync, v2.1.2
minimap, v4.12.1
python-tools, v0.6.7
todo-show, v1.4.0
tree-view-git-status, v0.1.2

# Dev
No dev packages
```
