### ISSUE TITLE
Empty TODO is causing todo-show to crash

### ISSUE THREAD

**Issue by vnglst** [mrodalgaard/atom-todo-show#114]
[Enter steps to reproduce below:]

1. Create an empty todo
2. Show todos
3. 💥

Uncaught TypeError: Cannot read property '1' of undefined
**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [todo-show](https://github.com/mrodalgaard/atom-todo-show) package, v1.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/vnglst/.atom/packages/todo-show/lib/todo-model.coffee:71

TypeError: Cannot read property '1' of undefined
    at TodoModel.module.exports.TodoModel.handleScanMatch (/Users/vnglst/.atom/packages/todo-show/lib/todo-model.coffee:71:65)
    at new TodoModel (/Users/vnglst/.atom/packages/todo-show/lib/todo-model.coffee:12:6)
    at /Users/vnglst/.atom/packages/todo-show/lib/todo-collection.coffee:106:22
    at Workspace.module.exports.Workspace.scan (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:989:11)
    at TodoCollection.module.exports.TodoCollection.fetchRegexItem (/Users/vnglst/.atom/packages/todo-show/lib/todo-collection.coffee:99:20)
    at TodoCollection.<anonymous> (/Users/vnglst/.atom/packages/todo-show/lib/todo-collection.coffee:163:28)
    at TodoCollection.module.exports.TodoCollection.search (/Users/vnglst/.atom/packages/todo-show/lib/todo-collection.coffee:160:22)
    at ShowTodoView.module.exports.ShowTodoView.initialize (/Users/vnglst/.atom/packages/todo-show/lib/todo-view.coffee:57:17)
    at ShowTodoView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at ShowTodoView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ShowTodoView (/Users/vnglst/.atom/packages/todo-show/lib/todo-view.coffee:52:5)
    at /Users/vnglst/.atom/packages/todo-show/lib/show-todo.coffee:82:13
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
    at Object.module.exports.show (/Users/vnglst/.atom/packages/todo-show/lib/show-todo.coffee:107:20)
    at atom-workspace.disposables.add.atom.commands.add.todo-show:find-in-project (/Users/vnglst/.atom/packages/todo-show/lib/show-todo.coffee:70:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:30.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:30.7.0 settings-view:view-installed-packages (atom-text-editor.editor)
     -1:18.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.7.0 pane:show-item-2 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-seti-ui)
  2x -0:52.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:49.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46.9.0 todo-show:find-in-project (atom-text-editor.editor)
  3x -0:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.3.0 todo-show:find-in-project (atom-text-editor.editor)
     -0:14.7.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:09.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 todo-show:find-in-project (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "htmlhint",
      "angularjs",
      "dash",
      "language-clojure"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "todo-show": {
    "sortAscending": false,
    "sortBy": "Type"
  }
}
```

### Installed Packages

```coffee
# User
atom-image-resize, v0.3.0
atom-jade, v0.3.0
autocomplete-modules, v1.4.1
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-eslint, v7.2.1
linter-less, v2.5.0
monokai, v0.18.0
react, v0.15.0
seti-ui, v0.9.2
todo-show, v1.5.0

# Dev
No dev packages
```

**Comment by vnglst** [comment]
Love your plugin btw!

**Comment by mrodalgaard** [comment]
I believe this fixes your problem, but I would like to know exactly how you created a todo match without a valid position. Could you make a more detailed step-by-step description to reproduce? Thank you.
