### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by menting311** [mrodalgaard/atom-todo-show#148]
[Enter steps to reproduce:]

1. Try to toggle on todo package for active files
2. ...

**Atom**: 1.14.0-beta0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [todo-show](https://github.com/mrodalgaard/atom-todo-show) package 1.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At C:\Users\tmenting\.atom\packages\todo-show\lib\todo-collection.coffee:154

TypeError: Cannot read property 'start' of undefined
    at /packages/todo-show/lib/todo-collection.coffee:154:31
    at ForwardsSingleLine.iterate (/app.asar/node_modules/text-buffer/lib/match-iterator.js:67:11)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:930:23)
    at TextBuffer.module.exports.TextBuffer.scan (/app.asar/node_modules/text-buffer/lib/text-buffer.js:898:19)
    at TextEditor.module.exports.TextEditor.scan (/app.asar/src/text-editor.js:2626:26)
    at TodoCollection.module.exports.TodoCollection.fetchOpenRegexItem (/packages/todo-show/lib/todo-collection.coffee:149:14)
    at /packages/todo-show/lib/todo-collection.coffee:185:25)
    at TodoCollection.module.exports.TodoCollection.search (/packages/todo-show/lib/todo-collection.coffee:184:22)
    at ShowTodoView.module.exports.ShowTodoView.initialize (/packages/todo-show/lib/todo-view.coffee:57:17)
    at /packages/todo-show/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/todo-show/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /packages/todo-show/lib/todo-view.coffee:52:5)
    at /packages/todo-show/lib/show-todo.coffee:92:13
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at Object.show (/packages/todo-show/lib/show-todo.coffee:121:20)
    at /packages/todo-show/lib/show-todo.coffee:80:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1158:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 61x -1:44 vim-mode:move-right (input.hidden-input)
     -1:35.4.0 vim-mode:activate-insert-mode (input.hidden-input)
     -1:28.7.0 vim-mode:activate-normal-mode (input.hidden-input)
  3x -1:28.5.0 vim-mode:reset-normal-mode (input.hidden-input)
     -1:25.4.0 vim-mode:search (input.hidden-input)
  3x -1:25.4.0 blur (input.hidden-input)
     -1:23.8.0 core:confirm (input.hidden-input)
  3x -1:23.8.0 blur (input.hidden-input)
     -1:21.7.0 vim-mode:repeat-search (input.hidden-input)
     -1:20.7.0 vim-mode:repeat-search-backwards (input.hidden-input)
  8x -1:11.4.0 vim-mode:move-down (input.hidden-input)
  5x -0:30.1.0 vim-mode:repeat-search (input.hidden-input)
     -0:17.2.0 todo-show:find-in-active-file (input.hidden-input)
  6x -0:17.2.0 blur (input.hidden-input)
     -0:05.1.0 todo-show:find-in-open-files (atom-pane.pane.active)
     -0:03.2.0 blur (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.29.16 
atom-copy-on-select 1.4.0 
atom-ctags 5.0.0 
atom-fuzzy-grep 0.15.0 
autocomplete-oracle 0.4.0 
blame 0.10.2 
ex-mode 0.13.1 
file-icons 2.0.8 
find-selection 0.16.0 
highlight-selected 0.12.0 
language-doxygen 0.2.1 
language-oracle 1.6.0 
linter 1.11.21 
linter-cppcheck 0.2.1 
minimap 4.26.6 
minimap-highlight-selected 4.5.0 
next-occurrence 0.5.0 
Sublime-Style-Column-Selection 1.7.2 
sync-settings 0.8.1 
todo-show 1.9.0 
tree-view-git-modified 0.7.1 
tree-view-git-status 1.3.0 
vim-mode 0.65.2 
```

**Comment by stephen-last** [comment]
I'm seeing this too!

**Atom:** 1.14.1 ia32
**OS:** Microsoft Windows 7 Pro
**Thrown From:** todo-show 1.9.0

```
C:\Users\stephen.last\.atom\packages\todo-show\lib\todo-collection.coffee:154

TypeError: Cannot read property 'start' of undefined
    at file:///C:/Users/stephen.last/.atom/packages/todo-show/lib/todo-collection.coffee:154:31
    at ForwardsSingleLine.iterate (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\text-buffer\lib\match-iterator.js:67:11)
    at TextBuffer.module.exports.TextBuffer.scanInRange (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:930:23)
    at TextBuffer.module.exports.TextBuffer.scan (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:898:19)
    at TextEditor.module.exports.TextEditor.scan (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\src\text-editor.js:2626:26)
    at TodoCollection.module.exports.TodoCollection.fetchOpenRegexItem (file:///C:/Users/stephen.last/.atom/packages/todo-show/lib/todo-collection.coffee:149:14)
    at TodoCollection.<anonymous> (file:///C:/Users/stephen.last/.atom/packages/todo-show/lib/todo-collection.coffee:185:25)
    at TodoCollection.module.exports.TodoCollection.search (file:///C:/Users/stephen.last/.atom/packages/todo-show/lib/todo-collection.coffee:184:22)
    at file:///C:/Users/stephen.last/.atom/packages/todo-show/lib/todo-view.coffee:110:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\src\pane-container.js:304:27)
    at Pane.module.exports.Pane.removeItem (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\src\pane.js:597:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\src\pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (C:\Users\stephen.last\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:222:19)

```

**Comment by jruota** [comment]
Same error here.

<p><strong>Atom: </strong>1.14.1<br />
<strong>Electron: </strong>1.3.13<br />
<strong>Chrome: </strong>52.0.2743.82<br />
<strong>Node: </strong> 6.5.0<br />
</p>
<h3>Stack Trace</h3>
<pre>
TypeError: Cannot read property 'start' of undefined
    at /home/jaro/.atom/packages/todo-show/lib/todo-collection.coffee:154:31
    at ForwardsSingleLine.iterate (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/match-iterator.js:67:11)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:930:23)
    at TextBuffer.module.exports.TextBuffer.scan (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:898:19)
    at TextEditor.module.exports.TextEditor.scan (/opt/atom/resources/app.asar/src/text-editor.js:2626:26)
    at TodoCollection.module.exports.TodoCollection.fetchOpenRegexItem (/home/jaro/.atom/packages/todo-show/lib/todo-collection.coffee:149:14)
    at TodoCollection.<anonymous> (/home/jaro/.atom/packages/todo-show/lib/todo-collection.coffee:186:27)
    at TodoCollection.module.exports.TodoCollection.search (/home/jaro/.atom/packages/todo-show/lib/todo-collection.coffee:184:22)
    at ShowTodoView.module.exports.ShowTodoView.initialize (/home/jaro/.atom/packages/todo-show/lib/todo-view.coffee:57:17)
    at ShowTodoView.View [as constructor] (/home/jaro/.atom/packages/todo-show/node_modules/space-pen/lib/space-pen.js:184:25)
    at ShowTodoView.ScrollView [as constructor] (/home/jaro/.atom/packages/todo-show/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ShowTodoView (/home/jaro/.atom/packages/todo-show/lib/todo-view.coffee:52:5)
    at /home/jaro/.atom/packages/todo-show/lib/show-todo.coffee:92:13
    at Workspace.module.exports.Workspace.openURIInPane (/opt/atom/resources/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/opt/atom/resources/app.asar/src/workspace.js:436:19)
    at Object.show (/home/jaro/.atom/packages/todo-show/lib/show-todo.coffee:121:20)
    at atom-workspace.disposables.add.atom.commands.add.todo-show:find-in-active-file (/home/jaro/.atom/packages/todo-show/lib/show-todo.coffee:81:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1158:28)
    at EventEmitter.outerCallback (/opt/atom/resources/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
</pre>
