### ISSUE TITLE
atom-to-show stopped working with ncaught (in promise) TypeError: target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by dbobak** [mrodalgaard/atom-todo-show#179]
The package stopped working, in the logs there is the following error:

```
Uncaught (in promise) TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\tooltip-manager.js:117:35)
    at ShowTodoView.module.exports.ShowTodoView.initialize (file:///C:/Users/deni/.atom/packages/todo-show/lib/todo-view.coffee:67:36)
    at ShowTodoView.View [as constructor] (C:\Users\deni\.atom\packages\todo-show\node_modules\space-pen\lib\space-pen.js:184:25)
    at ShowTodoView.ScrollView [as constructor] (C:\Users\deni\.atom\packages\todo-show\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new ShowTodoView (file:///C:/Users/deni/.atom/packages/todo-show/lib/todo-view.coffee:52:5)
    at TodoShow.deserializeTodoView (C:\Users\deni\.atom\packages\todo-show\lib\todo-show.js:49:25)
    at disposables.add.atom.workspace.addOpener.uri (C:\Users\deni\.atom\packages\todo-show\lib\todo-show.js:27:21)
    at Workspace.createItemForURI (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:1324:28)
    at Workspace.<anonymous> (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:1130:42)
    at Generator.next (<anonymous>)
    at step (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:11:279)
    at C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:11:449
    at Workspace.<anonymous> (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:11:105)
    at Workspace.toggle (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\workspace.js:1248:27)
    at TodoShow.show (C:\Users\deni\.atom\packages\todo-show\lib\todo-show.js:87:20)
    at HTMLElement.todo-show:toggle (C:\Users\deni\.atom\packages\todo-show\lib\todo-show.js:18:43)
    at CommandRegistry.handleCommandEvent (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\command-registry.js:388:36)
    at CommandRegistry.dispatch (C:\Users\deni\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\command-registry.js:273:23)
    at HTMLDivElement.module.exports.TabNumbersView.activateTodoPackage (file:///C:/Users/deni/.atom/packages/todo-show/lib/todo-indicator-view.coffee:33:19)
    at HTMLDivElement.dispatch (C:\Users\deni\.atom\packages\todo-show\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\deni\.atom\packages\todo-show\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by mrodalgaard** [comment]
Seems to be an error in the Atom tooltip manager. This only happened once, right?
