### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'isEqual' of undefined

### ISSUE THREAD

**Issue by X-Raym** [mrodalgaard/atom-todo-show#198]
Hi, I have a bug when activating Settings->Editor->Scroll past end option, when todo-show is active.

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

**Uncaught TypeError: Cannot read property 'isEqual' of undefined**

```
At C:\Users\Anymord\AppData\Local\atom\app-1.26.0\resources\app\src\text-editor-registry.js:261

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (~/AppData/Local/atom/app-1.26.0/resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (~/AppData/Local/atom/app-1.26.0/resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1226:62)
    at Config.setRawValue (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1052:23)
    at Config.set (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:715:18)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/settings-panel.js:238:34)
    at HTMLInputElement.changeHandler (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-lupa 0.7.43 
autoupdate-packages 1.3.1 
browser-plus 0.0.98 
busy-signal 1.4.3 
click-link 1.0.11 
color-tabs 0.1.8 
compare-files 0.8.1 
docblockr 0.13.7 
file-icons 2.1.19 
fountain 0.7.2 
git-diff-details 1.4.0 
git-time-machine 1.5.9 
highlight-bad-chars 1.0.7 
highlight-nbsp 0.1.1 
intentions 1.1.5 
language-generic-config 1.4.0 
language-lua 0.9.11 
language-reaperlangpack 0.0.1 
language-srt 0.1.1 
linter 2.2.0 
linter-js-standard 5.0.0 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
minimap 4.29.8 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
pane-browser 1.6.0 
pdf-view 0.69.0 
pigments 0.40.2 
quick-highlight 0.13.0 
script 3.18.0 
snippet-generator 0.3.2 
sort-lines 0.18.0 
source-preview 0.5.3 
space-tab 0.4.2 
split-diff 1.5.2 
standard-formatter 2.8.0 
symbols-tree-view 0.14.0 
tab-control 0.6.10 
tab-smart-sort 0.3.0 
teletype 0.13.1 
todo-show 2.3.0 
trailing-spaces 0.4.0 
tree-view-filter 0.5.3 
vtt-helper 0.1.1 
wordcount 2.10.4 
wordpress-api 1.2.2 
```

Can anyone reproduce ? Thanks !

**Comment by matrixik** [comment]
Also peoples in https://github.com/atom/atom/issues/16394 was reporting this problem and found out that todo-show have this problem.

**Comment by mrodalgaard** [comment]
This issue came from a deprecated way of creating and using a text editor inside the todo view. I have removed the search field for now until I have the time to update the whole view. Thank you all for coming with the feedback.

**Comment by ThomasLandauer** [comment]
For anybody needing the search functionality: https://atom.io/packages/todo supports it
