### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dmitruksergey** [mrodalgaard/atom-todo-show#70]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [todo-show](https://github.com/jamischarles/atom-todo-show) package, v0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/dmitruksergey/.atom/packages/todo-show/lib/show-todo-view.coffee:283

TypeError: Cannot read property '0' of undefined
  at /Users/dmitruksergey/.atom/packages/todo-show/lib/show-todo-view.coffee:283:61
  at Array.map (native)
  at ShowTodoView.module.exports.ShowTodoView.getMarkdown (/Users/dmitruksergey/.atom/packages/todo-show/lib/show-todo-view.coffee:275:14)
  at ShowTodoView.module.exports.ShowTodoView.saveAs (/Users/dmitruksergey/.atom/packages/todo-show/lib/show-todo-view.coffee:296:41)
  at HTMLAnchorElement.<anonymous> (/Users/dmitruksergey/.atom/packages/todo-show/lib/show-todo-view.coffee:252:8)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:42.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:41.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:41.2.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:36.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:36.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:35.6.0 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:34.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:33.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:33.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:27.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:21.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:19 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:18 todo-show:find-in-project (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      "._*",
      "*.hot-update.*",
      ".hgcheck",
      ".hg"
    ],
    "projectHome": "/Users/dmitruksergey/src/",
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "todo-show": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-jade, v0.3.0
atom-runner, v2.4.1
editorconfig, v1.0.1
emmet, v2.3.12
react, v0.12.5
snippets, v0.95.0
space-tab, v0.4.2
todo-show, v0.13.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by mrodalgaard** [comment]
I wonder how you managed to create a todo without a range, hehe.

I can see it happens when you try to save the list. Can you reproduce this? Else I'm just gonna add some extra checks when creating the markdown output.

**Comment by florianb** [comment]
I'd like to reopen this issue (https://gist.github.com/florianb/bb04eb5830615f5f5b14)

**Comment by mrodalgaard** [comment]
@florianb please try the newly released version and verify if this still happens. Otherwise I need to know exactly what you do to reproduce.
